#ifndef EXECUTE_FILES_H
#define EXECUTE_FILES_H

#include "configurations.h"

/*
 * Function Name: execute_ob
 * ----------------------------
 * This function writes the machine code generated by the assembler to an
 * output file in the object Code (.ob) format.
 *
 * file_name: a string representing the name of the assembly file.
 *
 * returns: true if the operation was successful, false otherwise.
 */
bool execute_ob(char *file_name);

/* 
 * Function Name: execute_ent
 * ----------------------------
 * This function writes the entries labels and their addresses to an 
 * output file in the Entries (.ent) format.
 *
 * file_name: a string representing the name of the assembly file.
 *
 * returns: true if the operation was successful, false otherwise.
 */
bool execute_ent(char *file_name);

/* 
 * Function Name: execute_ext
 * ----------------------------
 * This function writes the external labels and their addresses to an 
 * output file in the Entries (.ent) format.
 *
 * file_name: a string representing the name of the assembly file.
 *
 * returns: true if the operation was successful, false otherwise.
 */
bool execute_ext(char *file_name);

/* 
 * Function Name: replaceZerosOnes
 * ----------------------------
 * This function takes a binary string as input and returns a new string
 * where each '0' is replaced with a period ('.') and each '1' is replaced with
 * a forward slash ('/').
 *
 * binaryStr: a pointer to the binary string to be processed.
 *
 * return: a pointer to the new string with '0's replaced by '.' and '1's replaced by '/'.
 */
char* replaceZerosOnes(char *binaryStr);

#endif 
