assembler: assembler.c preAssembler.c utils.c firstPass.c secondPass.c configurations.c passesUtils.c executeFiles.c
	gcc -g -ansi -pedantic -Wall assembler.c preAssembler.c utils.c firstPass.c secondPass.c configurations.c passesUtils.c executeFiles.c -o assembler
